### ISSUE TITLE
Getting a liquid exception after bundle installing octopress-linkblog

### ISSUE THREAD

**Issue by adamstac** [octopress/linkblog#6]
Hey bro, I'm getting this error `Liquid Exception: no implicit conversion of nil into String` after adding this gem.

I added the gem, added the config details and tried to run Jekyll and get that error on the first post when Jekyll spins up.

Any thoughts on what this might be?

**Comment by imathis** [comment]
I'm not sure. I'll try to look into it tomorrow. Thanks for the heads up.

**Comment by adamstac** [comment]
Cool. I can help by troubleshooting more on my side too if need be. Let me know, and I'll be glad to help out.

**Comment by iphoting** [comment]
Would this error be related to the switch from Jekyll v2 to v3? I got the same error once I bumped Jekyll to v3:

```
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Deprecation: Collection#empty? should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:163:in `posts?'.
       Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:171:in `linkposts?'.
       Deprecation: Collection#empty? should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:163:in `posts?'.
       Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:171:in `linkposts?'.
       Deprecation: Collection#empty? should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:163:in `posts?'.
       Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:171:in `linkposts?'.
       Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-linkblog-2.0.2/lib/octopress-linkblog.rb:18:in `merge_payload'.
       Deprecation: Collection#reject should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-linkblog-2.0.2/lib/octopress-linkblog.rb:19:in `merge_payload'.
       Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-linkblog-2.0.2/lib/octopress-linkblog.rb:18:in `merge_payload'.
       Deprecation: Collection#reject should be called on the #docs array directly.
                    Called by /usr/local/rvm/gems/ruby-2.2.2@octopress3/gems/octopress-linkblog-2.0.2/lib/octopress-linkblog.rb:19:in `merge_payload'.
  Liquid Exception: no implicit conversion of nil into String in _posts/2007-09-07-Going-On.markdown
jekyll 3.0.1 | Error:  no implicit conversion of nil into String
```

Hope this helps!

**Comment by chrisfinazzo** [comment]
Yeah, just ran into this. Tracing the output gives the following information: 

<img width="1440" alt="screen shot 2015-12-17 at 12 10 44 pm" src="https://cloud.githubusercontent.com/assets/1534882/11876343/431e3d6e-a4b7-11e5-96c6-315f9578af98.png">

See also: Jekyll [#4199](https://github.com/jekyll/jekyll/issues/4199) for the fix related to the deprecation warning.

**Comment by mattrubin** [comment]
I believe this is the issue fixed by https://github.com/octopress/hooks/pull/14.
